name: book_summary_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  page_view_dot_indicator: ^2.3.0
  flutter_svg: ^2.0.15
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  animate_do: ^3.3.4
  oxidized: ^6.2.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
